Budeget/Budeget/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

Budeget/buget/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
]

Budeget/main/urls.py
from django.urls import path
from .views import *

app_name = 'main'

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("update/<pk>", PlansUpdate.as_view(), name="update"),
    path("delete/<pk>", PlansDelete.as_view(), name="delete"),
    path("pay/<id>", pay, name="pay"),
]

Budeget/main/models.py
from django.db import models

# Create your models here.


class MyBuget(models.Model):
    total = models.IntegerField('total',default=0)
    spent = models.IntegerField('spent',default=0)
    actions = models.IntegerField('actions',default=0)

    def __str__(self):
        return str(self.total)


class Plans(models.Model):
    name = models.CharField('name', max_length=150)
    comment = models.CharField('comment', max_length=450)
    spent = models.IntegerField('spent money')
    payed = models.BooleanField('payed/not payed',default=False)

    def __str__(self):
        return self.name
    
    

Budeget/main/forms.py
from django import forms
from .models import *

class AddPlan(forms.ModelForm):

    class Meta:
        model = Plans
        fields = ['name', 'comment', 'spent']

Budeget/main/views.py
from django.shortcuts import render, redirect
from django.views.generic import View, UpdateView, DeleteView
from .forms import *
from .models import *

# Create your views here.

class HomeView(View):

    def get(self, request):
        form = AddPlan(request.GET)
        plans = Plans.objects.all().order_by('-id')
        buget = MyBuget.objects.last()
        context = {
            'buget':buget,
            'form':form,
            'plans':plans,
        }
        return render(request, 'home.html', context)

    def post(self, request):
        form = AddPlan(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
        else:
            form = AddPlan()
        context = {
            'form':form,
        }
        return render(request, 'home.html', context)


class PlansUpdate(UpdateView):
    model = Plans
    form_class = AddPlan
    success_url = '/'
    template_name = 'update.html'

class PlansDelete(DeleteView):
    model = Plans
    success_url = '/'
    template_name = 'delete.html'

def pay(request, id):
    plan = Plans.objects.get(id=id)
    buget = MyBuget.objects.last()
    if plan.payed == False:
        minus = buget.total - plan.spent
        buget.total = minus
        buget.spent += plan.spent
        buget.actions += 1
        buget.save()
        plan.payed = True
        plan.save()
        return redirect('/')
    else:
        pass

Budeget/templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Delete</title>
</head>
<body>
    <form action="" method="POST">
        <center>

            <div class="mt-5">
                {% csrf_token %}
                <h1>Are you sure?</h1>
                <button type="submit" class="btn btn-danger">delete</button>
                <a href="{% url 'main:home' %}" class="btn btn-dark">go back</a>
            </div>
        </center>

    </form>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

Budeget/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Buget plans</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

</head>
<body>
    <div class="container">
        <div class="row mt-5">
            <div class="col-md-4">
                <div class="card bg-primary text- p-3" style="color: springgreen; background-color: ; box-shadow: 0px 5px 0px  springgreen;">
                    <div style="width: 0px; position: absolute; left: 260px; top: 30px;" class="btn btn-"><i style="font-size: 50px; color:springgreen;" class="far fa-money-bill-alt"></i></div>
                    <h4>My total sum</h4>
                    <h1>{{buget.total}}$</h1>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card bg-primary text- p-3" style="color: springgreen; box-shadow: 0px 5px 0px  springgreen;">
                    <div style="width: 0px; position: absolute; left: 260px; top: 30px;" class="btn btn-"><i style="font-size: 50px; color:springgreen;" class="fas fa-comments-alt-dollar"></i></div>
                    <h4>My total spent</h4>
                    <h1>{{buget.spent}}$</h1>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card bg-primary text- p-3" style="color: springgreen; box-shadow: 0px 5px 0px  springgreen;">
                    <div style="width: 0px; position: absolute; left: 260px; top: 30px;" class="btn btn-"><i style="font-size: 50px; color:springgreen;" class="fas fa-donate"></i></div>
                    <h4>My total actions</h4>
                    <h1>{{buget.actions}}</h1>
                </div>
            </div>
        
            <div class="row mt-5">
                <div class="col-lg-12">
                    <button type="button" class="btn btn-primary btn-block" data-bs-toggle="modal" data-bs-target="#exampleModal">
                        Add to plan
                      </button>
                    <!-- Button trigger modal -->
  
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <form action="" method="POST">

            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Add your Plan</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    {% csrf_token %}
                    {{form}}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </div>

        </form>
    </div>
  </div>
                </div>
            </div>

            <div class="row mt-5">
                
                {% for p in plans %}
                <div class="col-md-4 mb-4">
                    <div class="card bg-success text-light">
                        <div class="card-header">
                            {{p.spent}}$
                        </div>
                        <div class="card-body">
                            
                            {% if p.payed == True %}
                            <del>
                                <h3>{{p.name}}</h3>
                                <p>{{p.comment}}</p>
                            </del>
                            {% else %}
                                <h3>{{p.name}}</h3>
                                <p>{{p.comment}}</p>
                            {% endif %}
                                
                        </div>
                        <div class="card-footer">
        
                                
                            <a href="{% url 'main:delete' p.pk %}" class="btn btn-danger"><i class="fas fa-trash-alt"></i></a>
                            
                            {% if p.payed == False %}
                                <a href="{% url 'main:pay' p.id %}" class="btn btn-primary"><i class="fas fa-clipboard-check"></i></a>
                                {% else %}
                                <a href="#" class="btn btn-primary disabled"><i class="fas fa-calendar-times"></i></a>
                            {% endif %}
                               
                        </div>
                    </div>
                </div>
                {% endfor %}
                    
                
            </div>
        </div>
    </div>

    <script>
        document.querySelector('#id_name').className='form-control mb-3'
        document.querySelector('#id_comment').className='form-control mb-3'
        document.querySelector('#id_spent').className='form-control mb-3'
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

Budeget/templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Update</title>
</head>
<body>
    
    <form action="" method="POST">

            <div class="mt-5 w-25 container">
                {% csrf_token %}
                {{form}}
                <button type="submit" class="btn btn-warning">update</button>
                <a href="{% url 'main:home' %}" class="btn btn-dark">go back</a>
            </div>

    </form>

    <script>
        document.querySelector('#id_name').className = 'form-control mb-2'
        document.querySelector('#id_comment').className = 'form-control mb-2'
        document.querySelector('#id_spent').className = 'form-control mb-2'
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>